function [BW,maskedImage] = segmentImage(I,mask1)
%segmentImage segments image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(IM,MASK) segments image IM using
%  auto-generated code from the imageSegmenter App starting from the initial
%  segmentation specified by binary mask MASK. The final segmentation is
%  returned in BW and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 09-Feb-2017
%----------------------------------------------------


% Evolve segmentation
BW = activecontour(I, mask1, 100, 'Chan-Vese');

% Form masked image from input image and segmented image.
maskedImage = I;
maskedImage(~BW) = 0;
end
