function [BW,maskedImage] = segmentImage1(I)
%segmentImage segments image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(IM) segments image IM using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 09-Feb-2017
%----------------------------------------------------


% Initialize segmentation with Otsu's threshold
level = graythresh(I);
mask1 = im2bw(I,level);
BW = mask1;

% Form masked image from input image and segmented image.
maskedImage = I;
maskedImage(~BW) = 0;
end
